apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: igc-java-gradle-test
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: gradle-image
        type: string
        default: gradle:jdk11
  steps:
    - name: build
      image: $(inputs.params.gradle-image)
      workingdir: $(inputs.resources.source.path)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -x
          ./gradlew assemble --no-daemon
    - name: test
      image: $(inputs.params.gradle-image)
      workingdir: $(inputs.resources.source.path)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -x
          ./gradlew testClasses --no-daemon
    - name: sonar-scan
      image: $(inputs.params.gradle-image)
      workingdir: $(inputs.resources.source.path)
      envFrom:
        - configMapRef:
            name: sonarqube-config
        - secretRef:
            name: sonarqube-access
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -x
          if [ -n "${SONARQUBE_URL}" ] && [ -n "${SONARQUBE_USER}" ] && [ -n "${SONARQUBE_PASSWORD}" ]; then
              ./gradlew -Dsonar.login=${SONARQUBE_USER} -Dsonar.password=${SONARQUBE_PASSWORD} -Dsonar.host.url=${SONARQUBE_URL} sonarqube
          else 
              echo "Skipping Sonar Qube step"
          fi
